services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "10000:10000"
    volumes:
      - ./Front:/app/Front
      - go_mod_cache:/root/go/pkg/mod
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  go_mod_cache:
